<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto

namespace Proto\Data;

/**
 * Protobuf type <code>proto.data.AuthController</code>
 */
interface AuthControllerInterface
{
    /**
     * Method <code>add</code>
     *
     * @param \Proto\Data\UserRegisterRequest $request
     * @return \Proto\Data\UserRegisterResponse
     */
    public function add(\Proto\Data\UserRegisterRequest $request);

    /**
     * Method <code>get</code>
     *
     * @param \Proto\Data\UserRequest $request
     * @return \Proto\Data\UserResponse
     */
    public function get(\Proto\Data\UserRequest $request);

}

