<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto

namespace Proto\Data;

/**
 * Protobuf enum <code>Proto\Data\User\Role</code>
 */
class User_Role
{
    /**
     * Generated from protobuf enum <code>ADMIN = 0;</code>
     */
    const ADMIN = 0;
    /**
     * Generated from protobuf enum <code>USER = 1;</code>
     */
    const USER = 1;
}

