<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto

namespace Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.data.UserRegisterResponse</code>
 */
class UserRegisterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool register = 1;</code>
     */
    private $register = false;

    public function __construct() {
        \GPBMetadata\Proto\Test::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool register = 1;</code>
     * @return bool
     */
    public function getRegister()
    {
        return $this->register;
    }

    /**
     * Generated from protobuf field <code>bool register = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRegister($var)
    {
        GPBUtil::checkBool($var);
        $this->register = $var;

        return $this;
    }

}

